"""Initial db structure

Revision ID: ae14cf12f0a6
Revises: 
Create Date: 2020-11-02 22:34:42.933165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae14cf12f0a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='player_auction'
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamname', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('funds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='player_auction'
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('middlename', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('player_type', sa.Enum('Batsman', 'Bowler', 'AllRounder', 'WicketKeeper', name='playerrole'), nullable=True),
    sa.Column('buyout', sa.Float(), nullable=True),
    sa.Column('start_price', sa.Float(), nullable=True),
    sa.Column('auctioned', sa.Boolean(), nullable=True),
    sa.Column('contract_period', sa.Float(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['player_auction.team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='player_auction'
    )
    op.create_table('auction_bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('when', sa.TIMESTAMP(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player_auction.player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['player_auction.team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='player_auction'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction_bids', schema='player_auction')
    op.drop_table('player', schema='player_auction')
    op.drop_table('team', schema='player_auction')
    op.drop_table('admin', schema='player_auction')
    # ### end Alembic commands ###
